// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuudwLHzF72Ylk_GOziY2KpQSGHVI4_k',
    appId: '1:709362305836:web:9da668e45b9d4a29c57a89',
    messagingSenderId: '709362305836',
    projectId: 'ma2-mini-project',
    authDomain: 'ma2-mini-project.firebaseapp.com',
    storageBucket: 'ma2-mini-project.firebasestorage.app',
    measurementId: 'G-9XM8PL2DZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP4sGW0sHh0iUiZdp7ICmcKogZ7tAEnSI',
    appId: '1:709362305836:android:4b105eb3a63ee794c57a89',
    messagingSenderId: '709362305836',
    projectId: 'ma2-mini-project',
    storageBucket: 'ma2-mini-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHhkQQT7yabszoCi8vVFHOWje_ILh1VSQ',
    appId: '1:709362305836:ios:e0d8d7383a714decc57a89',
    messagingSenderId: '709362305836',
    projectId: 'ma2-mini-project',
    storageBucket: 'ma2-mini-project.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );
}
